### ISSUE TITLE
after ndk-build command "jni/../readline/tilde.c:423: error: undefined reference to 'endpwent'"

### ISSUE THREAD

**Issue by cn0xroot** [marcv81/proxdroid#2]
[armeabi] Compile thumb  : readline <= mbutil.c
[armeabi] Compile thumb  : readline <= tilde.c
[armeabi] SharedLibrary  : libreadline.so
jni/../readline/tilde.c:423: error: undefined reference to 'endpwent'
collect2: error: ld returned 1 exit status
make: **\* [obj/local/armeabi/libreadline.so] Error 1

OSX EI  10.11

**Comment by marcv81** [comment]
In readline/config.h there is the following.

```
/* Define if you have the getpwent function. */
#define HAVE_GETPWENT 1
```

Years ago when I last compiled this project getpwent() was available in the SDK. It seems it no longer is. You could try undefining HAVE_GETPWENT.

I'm going to close this issue as this project is currently unmaintained (i.e.: I don't have the HW anymore). For support please refer to the friendly proxmark forum: http://www.proxmark.org/forum/index.php.

**Comment by maikka39** [comment]
This worked for me
