### ISSUE TITLE
Error: expecting ')' + future maintance / development

### ISSUE THREAD

**Issue by KitsuneDev** [marcv81/proxdroid#3]
Good Evening,
I'm getting the following error while running `ndk-build` on OSX:
```
jni/../proxmark3/client/nonce2key/crapto1.h:79:35: error: expected ')'

                "movzx %%al, %0\n": "=r"(x) : "r"(x): "eax","ecx”);
                                  ^
jni/../proxmark3/client/nonce2key/crapto1.h:73:12: note: to match this '('

        asm(    "movl %1, %%eax\n"

           ^


```
I tried to fix it, but I don't understand what's wrong.
Also, I just bought a Proxmark3, so, if you want, I can maintain and continue ProxDroid development.
Thank you,
Gabriel

**Comment by marcv81** [comment]
As you noticed I am not maintaing this project anymore (i.e.: I no longer have the HW). I added you to the contributors list if you would like to fix things.

You might be able to get further support on the friendly proxmark forum: http://www.proxmark.org/forum/index.php. You might also find a solution to this problem in one of the forks of this repository.
